//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmSMv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Security.Cryptography;
    using System.Text;

    public partial class Farmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farmer()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int farmer_id { get; set; }

        [Required(ErrorMessage = "Please fill in your username")]
        [Display(Name = "Full Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Please fill in your address")]
        [Display(Name = "Address")]
        public string address { get; set; }
        [Required(ErrorMessage = "Please fill in your Phone Number")]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string phone_number { get; set; }
        [Required(ErrorMessage = "Please fill in your Email")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string email_address { get; set; }

        private string Password;

        [Required(ErrorMessage = "Please enter your password")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password
        {
            get { return Password; }
            set { Password = EncodePassword(value); }
        }

        //-------------------------------------------------------------------------//
        //Encrption for passwords 
        private string EncodePassword(string password)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] passwordBytes = Encoding.UTF8.GetBytes(password);
                byte[] hashBytes = sha256.ComputeHash(passwordBytes);
                return Convert.ToBase64String(hashBytes);
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
