//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmSMv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Display(Name = "Product ID")]
        public int product_id { get; set; }
        public int farmer_id { get; set; }
        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "Please fill in your Name")]
        public string name { get; set; }
        [Display(Name = "Product Price")]
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Please fill in the Product Price")]

        public Nullable<decimal> price { get; set; }
        [Display(Name = "Quantity")]
        [Required(ErrorMessage = "Please fill in the Quantity")]
        public Nullable<int> quantity_available { get; set; }
        [Display(Name = "Date Added")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please select the Date")]
        public System.DateTime date_added { get; set; }
        [Display(Name = "Date sold")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please select the Date")]
        public Nullable<System.DateTime> date_removed { get; set; }
        [Display(Name = "Product Type")]
        [Required(ErrorMessage = "Please select a type")]
        public int product_type_id { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
